### ISSUE TITLE
undefined method `y' for nil:NilClass

### ISSUE THREAD

**Issue by floydj** [prawnpdf/prawn-table#20]
This call fails after upgrading from 0.1.0 to 0.1.1:

``` ruby
table(rows, header: true, width: 465, cell_style: { border_width: 0, inline_format: true })
```

How can I fix?
